models.py
from __future__ import division

import random

import numpy as np

import otree.models
from otree.db import models
from otree import widgets
from otree.common import Currency as c, currency_range, safe_json
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer


author = 'Kathi'

doc = """
Letter Counting Task - Control Group
"""


class Constants(BaseConstants):
    name_in_url = 'Letter_Count'
    players_per_group = 5
    num_rounds = 1

    t = 20

# this defines and describes the payment methods. Make sure, the name of "Token" is defined in settings.py
    eurosper_token = 0.10
    tokensper_string = c(10)
    secondsper_token = 10

    # Define and describe tech increases and switch methods
    char_increase = 4

class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    output = models.PositiveIntegerField()

    #This defines the choices for the Questionnaire
    luck = models.PositiveIntegerField(
        choices=[
            [1, 'Not at all'],
            [2, ''],
            [3, ''],
            [4, ''],
            [5, ''],
            [6, ''],
            [7, ''],
            [8, ''],
            [9, ''],
            [10, ''],
        ],
        # horizontal radio button instead of selection
        widget=widgets.RadioSelectHorizontal()
    )
    #This defines the choices for the Questionnaire
    skill = models.PositiveIntegerField(
        choices=[
            [1, '1'],
            [2, '2'],
            [3, '3'],
            [4, '4'],
            [5, '5'],
            [6, '6'],
            [7, '7'],
            [8, '8'],
            [9, '9'],
            [10, '10'],
        ],
        # horizontal radio button instead of selection
        widget=widgets.RadioSelectHorizontal()
    )

    output0 = models.PositiveIntegerField()
    output1 = models.PositiveIntegerField()
    output2 = models.PositiveIntegerField()
    output3 = models.PositiveIntegerField()
    output4 = models.PositiveIntegerField()
    output5 = models.PositiveIntegerField()
    output6 = models.PositiveIntegerField()
    output7 = models.PositiveIntegerField()
    output8 = models.PositiveIntegerField()
    share3 = models.FloatField()
    share4 = models.FloatField()
    share5 = models.FloatField()
    share6 = models.FloatField()
    share7 = models.FloatField()
    share8 = models.FloatField()
    st1 = models.PositiveIntegerField()
    st2 = models.PositiveIntegerField()
    st3 = models.PositiveIntegerField()
    st4 = models.PositiveIntegerField()
    st5 = models.PositiveIntegerField()
    st6 = models.PositiveIntegerField()
    st7 = models.PositiveIntegerField()
    st8 = models.PositiveIntegerField()
    t001 = models.CharField()
    t002 = models.CharField()
    t003 = models.CharField()
    t004 = models.CharField()
    t005 = models.CharField()
    t101 = models.CharField()
    t102 = models.CharField()
    t103 = models.CharField()
    t104 = models.CharField()
    t105 = models.CharField()
    t106 = models.CharField()
    t107 = models.CharField()
    t108 = models.CharField()
    t109 = models.CharField()
    t110 = models.CharField()
    t111 = models.CharField()
    t112 = models.CharField()
    t113 = models.CharField()
    t114 = models.CharField()
    t115 = models.CharField()
    t116 = models.CharField()
    t117 = models.CharField()
    t118 = models.CharField()
    t119 = models.CharField()
    t120 = models.CharField()
    t121 = models.CharField()
    t122 = models.CharField()
    t123 = models.CharField()
    t124 = models.CharField()
    t125 = models.CharField()
    t126 = models.CharField()
    t127 = models.CharField()
    t128 = models.CharField()
    t129 = models.CharField()
    t130 = models.CharField()
    t201 = models.CharField()
    t202 = models.CharField()
    t203 = models.CharField()
    t204 = models.CharField()
    t205 = models.CharField()
    t206 = models.CharField()
    t207 = models.CharField()
    t208 = models.CharField()
    t209 = models.CharField()
    t210 = models.CharField()
    t211 = models.CharField()
    t212 = models.CharField()
    t213 = models.CharField()
    t214 = models.CharField()
    t215 = models.CharField()
    t216 = models.CharField()
    t217 = models.CharField()
    t218 = models.CharField()
    t219 = models.CharField()
    t220 = models.CharField()
    t221 = models.CharField()
    t222 = models.CharField()
    t223 = models.CharField()
    t224 = models.CharField()
    t225 = models.CharField()
    t226 = models.CharField()
    t227 = models.CharField()
    t228 = models.CharField()
    t229 = models.CharField()
    t230 = models.CharField()
    t301 = models.CharField()
    t302 = models.CharField()
    t303 = models.CharField()
    t304 = models.CharField()
    t305 = models.CharField()
    t306 = models.CharField()
    t307 = models.CharField()
    t308 = models.CharField()
    t309 = models.CharField()
    t310 = models.CharField()
    t311 = models.CharField()
    t312 = models.CharField()
    t313 = models.CharField()
    t314 = models.CharField()
    t315 = models.CharField()
    t316 = models.CharField()
    t317 = models.CharField()
    t318 = models.CharField()
    t319 = models.CharField()
    t320 = models.CharField()
    t321 = models.CharField()
    t322 = models.CharField()
    t323 = models.CharField()
    t324 = models.CharField()
    t325 = models.CharField()
    t326 = models.CharField()
    t327 = models.CharField()
    t328 = models.CharField()
    t329 = models.CharField()
    t330 = models.CharField()
    t401 = models.CharField()
    t402 = models.CharField()
    t403 = models.CharField()
    t404 = models.CharField()
    t405 = models.CharField()
    t406 = models.CharField()
    t407 = models.CharField()
    t408 = models.CharField()
    t409 = models.CharField()
    t410 = models.CharField()
    t411 = models.CharField()
    t412 = models.CharField()
    t413 = models.CharField()
    t414 = models.CharField()
    t415 = models.CharField()
    t416 = models.CharField()
    t417 = models.CharField()
    t418 = models.CharField()
    t419 = models.CharField()
    t420 = models.CharField()
    t421 = models.CharField()
    t422 = models.CharField()
    t423 = models.CharField()
    t424 = models.CharField()
    t425 = models.CharField()
    t426 = models.CharField()
    t427 = models.CharField()
    t428 = models.CharField()
    t429 = models.CharField()
    t430 = models.CharField()
    t501 = models.CharField()
    t502 = models.CharField()
    t503 = models.CharField()
    t504 = models.CharField()
    t505 = models.CharField()
    t506 = models.CharField()
    t507 = models.CharField()
    t508 = models.CharField()
    t509 = models.CharField()
    t510 = models.CharField()
    t511 = models.CharField()
    t512 = models.CharField()
    t513 = models.CharField()
    t514 = models.CharField()
    t515 = models.CharField()
    t516 = models.CharField()
    t517 = models.CharField()
    t518 = models.CharField()
    t519 = models.CharField()
    t520 = models.CharField()
    t521 = models.CharField()
    t522 = models.CharField()
    t523 = models.CharField()
    t524 = models.CharField()
    t525 = models.CharField()
    t526 = models.CharField()
    t527 = models.CharField()
    t528 = models.CharField()
    t529 = models.CharField()
    t530 = models.CharField()
    t601 = models.CharField()
    t602 = models.CharField()
    t603 = models.CharField()
    t604 = models.CharField()
    t605 = models.CharField()
    t606 = models.CharField()
    t607 = models.CharField()
    t608 = models.CharField()
    t609 = models.CharField()
    t610 = models.CharField()
    t611 = models.CharField()
    t612 = models.CharField()
    t613 = models.CharField()
    t614 = models.CharField()
    t615 = models.CharField()
    t616 = models.CharField()
    t617 = models.CharField()
    t618 = models.CharField()
    t619 = models.CharField()
    t620 = models.CharField()
    t621 = models.CharField()
    t622 = models.CharField()
    t623 = models.CharField()
    t624 = models.CharField()
    t625 = models.CharField()
    t626 = models.CharField()
    t627 = models.CharField()
    t628 = models.CharField()
    t629 = models.CharField()
    t630 = models.CharField()
    t701 = models.CharField()
    t702 = models.CharField()
    t703 = models.CharField()
    t704 = models.CharField()
    t705 = models.CharField()
    t706 = models.CharField()
    t707 = models.CharField()
    t708 = models.CharField()
    t709 = models.CharField()
    t710 = models.CharField()
    t711 = models.CharField()
    t712 = models.CharField()
    t713 = models.CharField()
    t714 = models.CharField()
    t715 = models.CharField()
    t716 = models.CharField()
    t717 = models.CharField()
    t718 = models.CharField()
    t719 = models.CharField()
    t720 = models.CharField()
    t721 = models.CharField()
    t722 = models.CharField()
    t723 = models.CharField()
    t724 = models.CharField()
    t725 = models.CharField()
    t726 = models.CharField()
    t727 = models.CharField()
    t728 = models.CharField()
    t729 = models.CharField()
    t730 = models.CharField()
    t801 = models.CharField()
    t802 = models.CharField()
    t803 = models.CharField()
    t804 = models.CharField()
    t805 = models.CharField()
    t806 = models.CharField()
    t807 = models.CharField()
    t808 = models.CharField()
    t809 = models.CharField()
    t810 = models.CharField()
    t811 = models.CharField()
    t812 = models.CharField()
    t813 = models.CharField()
    t814 = models.CharField()
    t815 = models.CharField()
    t816 = models.CharField()
    t817 = models.CharField()
    t818 = models.CharField()
    t819 = models.CharField()
    t820 = models.CharField()
    t821 = models.CharField()
    t822 = models.CharField()
    t823 = models.CharField()
    t824 = models.CharField()
    t825 = models.CharField()
    t826 = models.CharField()

templates/Letter_Count/Competition_Instructions_3.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Part 2 (3/3)
{% endblock %}

{% block content %}

    <p>
        After each round, you will get feedback about the number of strings you solved and the technology you used.</p>
    <p>
        After completion of part 2 you will be asked to fill out a short survey before the experiment is finished.</p>
    <p>
        Press "Next" when you have read and understood these instructions.
	     After you have pressed the "Next"-button you may still need to wait for other participants to get ready.
    </p>

    {% next_button %}

{% endblock %}

templates/Letter_Count/FeedbackC2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}



{% block styles %}

<!-- CSS Styling for Table: If you want to uncomment -> comment Bootstrap in content

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#999;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#444;background-color:#F7FDFA;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#fff;background-color:#26ADE4;}
.tg .tg-s6z2{text-align:center}
@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>

-->

<!-- CSS Styling for Box around Text: Will use Bootstrap Panel

<style>
.border
{
border:1px;
border-style:solid;
border-color:#287EC7;
padding: 1em;
}
</style>


-->

{% endblock %}


{% block title %}
    Your Results in Period <!-- insert "t" number of period-->
{% endblock %}

{% block content %}
<p class="alert alert-warning"> The next period will begin in
    <!-- Insert Clock -->
</p>

<p class="alert alert-warning"> Your technology for the next periods is <!-- basic/advanced --></p>

<br>

<!-- if player in treatment, also -->


<div class="panel panel-primary">
  <div class="panel-heading"> In this period you solved: </div>
  <div class="panel-body">
    <!-- number of correct strings --> strings. Therefore, in this period you earned
    <!-- number of correct strings * tokens/string--> tokens. <br>
     For the time spent in switch mode in this period you earned: <!-- seconds in switch mode --> tokens. <br>
    <b>Your total earnings in this period are therefore: <!-- tokens strings + tokens switch mode --> tokens.</b> <br>
</p>
  </div>
</div>

<!-- if player in treatment, also -->

<!-- Bootstrap Table Design -->

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Group Results</div>
  <div class="panel-body">
    Here you can see the performance during this period of the other participants in your group:
  </div>


<!-- Begin Table -->
<table class="table">
  <thead>
  <tr>
    <th class="tg-s6z2">Rank</th>
    <th class="tg-s6z2">Player</th>
    <th class="tg-s6z2">Production*</th>
    <th class="tg-s6z2">Share of Group Production+</th>
  </thead>
  </tr>
  <tr>
    <td class="tg-s6z2">1</td>
    <td class="tg-s6z2"><br></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
  </tr>
  <tr>
    <td class="tg-s6z2">2</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
  </tr>
  <tr>
    <td class="tg-s6z2">3</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
  </tr>
  <tr>
    <td class="tg-s6z2">4</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
  </tr>
  <tr>
    <td class="tg-s6z2">5</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2"></td>
  </tr>
  <tfoot>
  <tr>
    <td class="tg-s6z2" colspan="2">Total</td>
    <td class="tg-s6z2"></td>
    <td class="tg-s6z2">100%</td>
  </tr>
  </tfoot>
</table>


<p>
* Production refers to the amount of correctly solved strings. <br>
** This is equal to the probability of achieving the advanced technology in the next period.
</p>

</div>

<!-- End Table -->


    {% next_button %}

{% endblock %}

templates/Letter_Count/Feedback_Round0.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Feedback Trial
{% endblock %}

{% block content %}

    <p>
        You solved {{ player.output0 }} strings.
    </p>

{% next_button %}

{% endblock %}

templates/Letter_Count/Feedback_Round1.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Feedback Part 1
{% endblock %}

{% block content %}

    <p>
        In this period you solved {{} player.output1|c }} sequences which earned you {{} player.output1|c }}.<br>
        You spent {{player.switcht1}} seconds in the <em>switch mode</em> which earned you {{player.switch1|c}}.</p>
    <p>
        Your total earnings of this period are therefore <strong>{{player.total1|c}}.</strong></p>

{% next_button %}

{% endblock %}

templates/Letter_Count/Feedback_Round2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Feedback Part 1
{% endblock %}

{% block content %}

    <p>
        In this period you solved {{ player.output2 }} sequences which earned you {{ player.output2|c }}.<br>
        You spent {{ player.switcht2 }} seconds in the <em>switch mode</em> which earned you {{ player.switch2|c }}.</p>
    <p>
        Your total earnings of this period are therefore <strong>{{player.total1|c}}.</strong></p>

{% next_button %}

{% endblock %}

templates/Letter_Count/Feedback_Round4.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}



{% block styles %}

<!-- CSS Styling for Table: If you want to uncomment -> comment Bootstrap in content

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#999;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#444;background-color:#F7FDFA;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#fff;background-color:#26ADE4;}
.tg .tg-s6z2{text-align:center}
@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>

-->

<!-- CSS Styling for Box around Text: Will use Bootstrap Panel

<style>
.border
{
border:1px;
border-style:solid;
border-color:#287EC7;
padding: 1em;
}
</style>


-->

{% endblock %}


{% block title %}
    Your Results in Period 2
{% endblock %}

{% block content %}

<p class="alert alert-warning"> Your technology for the next periods is <strong>advanced</strong>.</p>

<br>


<div class="panel panel-primary">
  <div class="panel-heading"> In this period you solved: </div>
  <div class="panel-body">
      8 strings. Therefore, in this period you earned 8 tokens. <br>
      For the time spent in switch mode in this period you earned: 3 tokens. <br>
      <b>Your total earnings in this period are therefore: 11 tokens.</b> <br>
</p>
  </div>
</div>


{% endblock %}

templates/Letter_Count/Round0.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
    <link href="{% static "LetterCount/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Trial Run
{% endblock %}

{% block content %}

<div id="string">
</div>

<br>

<input type="text" id="player_guess" size="4" autofocus>
</input> &nbsp;
<span id="min">00</span>:<span id="sec">00</span>
&nbsp; Time spent in the current string

<br>

<input type="hidden" name="output0" id="id_output0"/>

</div>
<div class="next_container">
    <input class="btn btn-primary btn-large btn-primary next-button" type="submit" value="Continue">
</div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'LetterCount/js/Round0.js' %}"></script>
{% endblock %}

templates/Letter_Count/Round2.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
    <link href="{% static "LetterCount/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Part 1 continued
{% endblock %}

{% block content %}

<div id="string">
</div>

<br>
<input type="text" id="player_guess" autofocus>
</input>

<span id="min">00</span>:<span id="sec">00</span>

<input type="hidden" name="output2" value="0" id="id_output2"/>

<p align="right">
    <button id="Switch_button" button = "button">Switch</button>
</p>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "LetterCount/js/Round2.js" %}"></script>

{% endblock %}

templates/Letter_Count/Round4b.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
    <link href="{% static "project2cont/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Period 2
{% endblock %}

{% block content %}

<div id="string">
</div>

<br>
<input type="text" id="player_guess" autofocus>
</input>

<span id="min">00</span>:<span id="sec">00</span>

<input type="hidden" name="output4b" value="0" id="id_output4b"/>

<p align="right">
    <button id="Switch_button" button = "button">Switch</button>
</p>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "project2cont/js/Round4b.js" %}"></script>
{% endblock %}

templates/Letter_Count/Round5b.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
    <link href="{% static "project2cont/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Period 3
{% endblock %}

{% block content %}

<div id="string">
</div>

<br>
<input type="text" id="player_guess" autofocus>
</input>

<span id="min">00</span>:<span id="sec">00</span>

<input type="hidden" name="output5b" value="0" id="id_output5b"/>

<p align="right">
    <button id="Switch_button" button = "button">Switch</button>
</p>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "project2cont/js/Round5b.js" %}"></script>
{% endblock %}

templates/Letter_Count/Round6a.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block styles %}
    <link href="{% static "project2cont/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Period 4
{% endblock %}

{% block content %}

<div id="string">
</div>

<br>
<input type="text" id="player_guess" autofocus>
</input>

<span id="min">00</span>:<span id="sec">00</span>

<input type="hidden" name="output6a" value="0" id="id_output6a"/>

<p align="right">
    <button id="Switch_button" button = "button">Switch</button>
</p>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static "project2cont/js/Round6a.js" %}"></script>
{% endblock %}

templates/Letter_Count/Task_Instructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Task Instructions
{% endblock %}

{% block content %}
<div class="instructions well well-lg">
    <p>
    During the experiment, you will be asked to count letters. You have to count <strong>how many</strong> times the letter “<strong>a</strong>“
    appears in a sequence of characters.</p>
    <p>
    Now you will have the opportunity to try the task five times. You will face various difficulties to get a good impression of the task.
    The timer next to the input field will tell you how long you take for each sequence. Also, try entering the wrong number of “<strong>a</strong>“-letters to see what happens.
    To submit a guess, press Enter.</p>
    <p>
    <p></p>
</div>
    {% next_button %}

{% endblock %}

templates/Letter_Count/Technology_Instructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Part 1 continued
{% endblock %}

{% block content %}

<div class="instructions well well-lg">
    <p>
        Now you will have another 4 minutes to earn Tokens by counting "<strong>a</strong>"- letters or
        by spending time in the <em>switch mode</em>.<br>
        Again, you will start solving short sequences. This time however, the <strong>length of the sequences will increase by only two characters</strong> after each sequence you have solved.</p>
    <p>
        From now on this will be called the <em>advanced techonology</em>.<br>
	      Last round you have used the <em>basic techonology</em> where the length of sequences increased by four characters.</p>
    <p>
        Remember that you can earn 1 Token by solving a character sequence or by spending {{ Constants.secondsper_token }} seconds in the <em>switch mode</em>.</p>
    <p>
        Ready? Now you have 4 minutes to earn Tokens.</p>
</div>
    {% next_button %}

{% endblock %}

templates/Letter_Count/Welcome.html
{% extends "global/Page.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}

    <p>
        Welcome to this experiment.
    </p>
    <p>
        Please press "Next" to indicate that you are ready to receive instructions.
    </p>

    {% next_button %}

{% endblock %}